### ISSUE TITLE
Error when taking Authorization header as user_id while adding to allow-list

### ISSUE THREAD

**Issue by Robb-Fr** [f5devcentral/f5xc-emea-workshop#100]
Following the lab in as described up to module 5 - lab 2, I received the following error when trying to add the purposefully generated malicious user to the list of allow listed users:
```
Http failure response: 400 Bad Request
Field user_id should have maximum length of 256, got 265 (value: "Header-Authorization-Bearer eyJ0eX[Shrinked ID Token]fn4") in request.
Field user_id fails rule ves.io.schema.rules.string.max_len constraint 256 due to value 265

https://f5-emea-workshop.console.ves.volterra.io/api/config/namespaces/trusty-goose/http_loadbalancers/arcadia-re-lb/trust_client/suggestion
```

This error is only raised when added the user to the allowed users list. (See attached screenshot) 
![Screenshot 2024-06-12 at 09-03-49 HTTP Load Balancer arcadia re-lb - Performance Web App   API Protection](https://github.com/f5devcentral/f5xc-emea-workshop/assets/43422546/162a6865-e860-4a9b-9a3b-6f51bd75c9a4)

This size limit makes sense, as well as using an Authorization header to identify users (although logging Tokens in clear which may not be best practice). Maybe this maximum size could be increased for the lab or the recommended logging information be taken elsewhere in order for students to not run into this error.

**Comment by sorinboia** [comment]
Step 4 - 6 on this page https://clouddocs.f5.com/training/community/f5xc-emea-workshop/html/class1/module5/lab2/lab2.html mention that the IP address of the client should be white listed, not the token.
